title: BitCurator
description: Software produced for the BitCurator family of research projects (BitCurator, BitCurator Access, BitCurator NLP).
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
